---
title: " "
---

Updated 2026-05-01

# Articles in indexed journals with impact factor (17)

[17] Dufresnes C., Conan A., Coquis A., Michon A., Vacher J.-P., Ursenbacher S., Jablonski
D. (2026). Mitochondrial tracing of amphibian introductions amid cyto-nuclear discordance :
a case study of two allochtonous populations of green toads. Amphibia-Reptilia, in press.
IF : 1.3

[16] Dayon J., Conan A., Dehaut N., Fizesan A., Guenier C., Pille F., Szollosy S., Vacher
J.-P., Vignon V., Miaud C. (2026). Combining telemetry and fluorescent pigments to
study the use of terrestrial habitats by a declining amphibian, the common spadefoot toad
(*Pelobates fuscus*). Amphibia-Reptilia, in press. IF : 1.3

[15] Vacher J.-P., Kok P.J.K., Rodrigues M.T., Lima J.D., Hrbek T., Werneck F.P.,
Manzi S., Thébaud C., Fouquet A. (2024). Diversification of the terrestrial frog genus
*Anomaloglossus* (Anura, Aromobatidae) in the Guiana Shield proceeded from highlands to
lowlands, with successive loss and reacquisition of endotrophy. Molecular Phylogenetics
and Evolution, 192 : 108008. IF : 4.1

[14] Vacher J.P., Graitson E., Cauwenbergh J., Ursenbacher S. (2022). Conservation
genetics of a wide-ranged temperate snake : same species, different locations, and different
behaviour. Conservation Genetics, 23 : 167-177. IF : 2.53

[13] Vacher J.P., Chave J., Ficetola F., Sommeria-Klein G., Tao S., Thébaud C., Blanc M.,
Camacho A., Cassimiro J., Colston T.J., Dewynter M., Ernst R., Gaucher P., Gomes J.O.,
Jairam R., Kok P.J.R., Dias Lima J., Martinez Q., Marty C., Noonan B.P., Nunes P.M.S.,
Ouboter P., Recoder R., Rodrigues M.T., Snyder A., de Souza S.M., Fouquet A. (2020).
Large scale DNA-based survey of frogs in Amazonia suggests a vast underestimation of
species richness and endemism. Journal of Biogeography, 47 (8): 1781-1791. IF : 3.72

[12] Vacher J.P., Aumaître D., Ursenbacher S. (2020). Genetic characteristics of an
introduced population of *Bombina bombina* (Linnaeus, 1761) (Amphibia: Bombinatoridae)
in Moselle, France. Acta Herpetologica, 15 (1): 47-54. IF : 0.69

[11] Vacher J.-P., Manzi S., Rodrigues M.T., Fouquet A. (2020). The complete mitochondrial
genome of *Iphisa elegans* (Reptilia: Squamata: Gymnophthalmidae). Mitochondrial
DNA Part B, 5 (3): 3106-3108. IF : 0.65

[10] Fouquet A., Vacher J.-P., Courtois E.A., Deschamps C., Ouboter P., Jairam R.,
Gaucher P., Dubois A., Kok P.J.R. (2019). A new species of *Anomaloglossus* (Anura:
Aromobatidae) of the stepheni group with the redescription of *A. baeobatrachus* (Boistel
and de Massary, 1999), and an amended definition of *A. leopardus* Ouboter and Jairam, 2012. Zootaxa, 4576 (3): 439-460. IF : 1.09

[9] Fouquet A., Ferrier, B., Salmona J., Tirera S., Vacher J.-P., Courtois E.A., Gaucher, P.,
Dias Lima J., Nunes P.M.S., de Souza S.M., Noonan B., de Thoisy B. (2019). Phenotypic
and life-history diversification in Amazonian frogs despite past introgressions. Molecular
Phylogenetics and Evolution, 130: 169-180. IF : 4.28

[8] Vacher J.P., Wendling T. (2019). An unusual case of predation by the western green
lizard *Lacerta bilineata* Daudin, 1802 (Squamata: Lacertidae) on the slow worm *Anguis
fragilis* Linnaeus, 1758 (Squamata: Anguidae). Herpetology Notes, 12: 1201-1202. IF :
0.68

[7] Fouquet A., Vacher J.-P., Courtois E.A., Villette B., Reizine H., Gaucher P., Jairam R.,
Ouboter P., Kok P. (2018). On the brink of extinction : two new species of *Anomaloglossus*
from French Guiana and amended definitions of *Anomaloglossus degranvillei* and *A.
surinamensis* (Anura: Aromobatidae). Zootaxa, 4379 (1): 1-23. IF : 1.09

[6] Vacher J.-P., Kok P.J.K., Rodrigues M.T., Lima J.D., Lorenzini A., Martinez Q., Fallet
M., Courtois E.A., Blanc M., Gaucher P., Dewynter M., Jairam R., Ouboter P., Thébaud
C., Fouquet A. (2017). Cryptic diversity in Amazonian frogs : Integrative taxonomy of
the genus *Anomaloglossus* (Amphibia: Anura: Aromobatidae) reveals a unique case of
diversification within the Guiana Shield. Molecular Phylogenetics and Evolution, 112 (2017):
158-173. IF : 4.28

[5] Vacher J.-P., Fouquet A., Holota H., Thébaud C. (2016). The complete mitochondrial
genome of *Anomaloglossus baeobatrachus* (Amphibia: Anura: Aromobatidae). Mitochondrial
DNA Part B : Resources, 1 (1): 400-402. IF : 0.65

[4] Fouquet A., Orrico V.G.D., Ernst R., Blanc M., Martinez Q., Vacher J.-P., Rodrigues
M.T., Ouboter P. Jairam R., Ron S. (2015). A new *Dendropsophus* Fitzinger, 1843 (Anura:
Hylidae) of the *parviceps* group from the lowlands of the Guiana Shield. Zootaxa, 4052
(1): 39-64. IF : 0.949

[3] Fouquet A., Vacher J.-P., Kadosoe V., Jairam R., Ouboter P. (2015). Checklist of
the amphibians of the Sipaliwini area, Suriname. Herpetology Notes, 8: 63-68. IF : 0.68

[2] Cayuela H., Lambrey J., Vacher J.-P., Miaud C. (2015). Highlighting the effects of
land-use change on a threatened amphibian in a human-dominated landscape. Population
Ecology, 57(2): 433-443. IF : 1.297

[1] Thienpont S., Vacher J.-P., Berroneau M., Miquet A., Barthe L., Caillebotte A., Lerat
D., Gendre T., Owen-Jones Z., Marandon J.-L., Quesada R. (2013). Conservation activities
for European pond turtles (*Emys orbicularis*) in France. Herpetology Notes, 6: 139-141.
IF : 0.97

# Articles in indexed journals without impact factor (35)

[35] Vacher J.-P., Valentini A., Dayon J., Aumaître D. (2026). Découverte d’un nouveau
taxon d’amphibien grâce à l’ADN environnemental : première mention de *Pelophylax*
(*ridibindus*) *kurtmuelleri* (Gayda, 1940) (Amphibia, Anura, Ranidae) en Lorraine et mise
à jour de la répartition dans le Grand Est. Bulletin de la Société d’Histoire naturelle de
Colmar (submitted).

[34] Vacher J.-P. (2025). Première mention de *Dolomedes plantarius* (Clerck, 1758)
(Arachnida, Araneae, Pisauridae) en Lorraine et mise à jour de sa répartition en Alsace.
Bulletin de la Société d’Histoire naturelle de Colmar, 81 (8) : 77-81.

[33] Clément V., Vacher J.-P. (2025). Note sur l’observation d’un Triton ponctué *Lissotriton
vulgaris* (Linnaeus, 1758) (Amphibia, Urodela, Salamandridae) pédomorphique dans
la vallée du Rhin en Alsace. Bulletin de la Société d’Histoire naturelle de Colmar, 81 (6) :
65-67.

[32] Lorrain-Soligon L., Bichain J.-M., Brischoux F., Vacher J.-P. (2023). Hitchhicking
freshwater clams : First report of Sphaerium nucleus attached to *Lissotriton helveticus* in
France. The Herpetological Bulletin, 166 : 23-24.

[31] Lorrain-Soligon L., Vacher J.-P., Brischoux F. (2023). Palmate newts *Lissotriton
helveticus* infected with Amphibiocystidum sp. in France. The Herpetological Bulletin,
165 : 27-28.

[30] Guiller G., Vacher J.-P. (2022). La prairie permanente non pâturée : un habitat
souvent délaissé pour la conservation des Squamates du bocage. Naturae, 10 : 193-203.

[29] Vacher J.-P., D’Agostino R., Ursenbacher S. (2021). Characterizing the taxonomic
status of *Sphingonotus caerulans* in the upper Rhine Valley of Alsace (France) (Orthoptera,
Acrididae, Oedipodinae). Bulletin de la Société Entomologique de France, 126 (4) : 513-519.

[28] D’Agostino R., Vacher J.-P. (2021). Évolution temporelle de la répartition des
Orthoptères dans le massif vosgien : possibles effets des changements climatiques sur la
biodiversité. Bulletin de la Société d’Histoire naturelle de Colmar, 77 (2) : 10-17.

[27] D’Agostino R., Vacher J.-P. (2020). Quelle espèce de *Sphingonotus* Fieber, 1852
(Insecta, Orthoptera, Acrididae) se trouve dans la plaine du Rhin ? Bulletin de la Société
d’Histoire naturelle de Colmar, 76 (5) : 18-24.

[26] Vacher J.-P. (2019). Note sur le statut taxinomique de la Coronelle lisse *Coronella
austriaca* Laurenti, 1768 (Reptilia: Serpentes: Colubridae) en Alsace. Bulletin de la Société
d’Histoire naturelle et d’Ethnographie de Colmar, 76 : 5-7.

[25] Berna A., Bret C., Vacher J.-P., Pottier G. (2016). Nouveau record d’altitude chez
la Couleuvre à collier *Natrix natrix* (Linnaeus, 1758) (Squamata, Natricidae) dans les
Pyrénées. Bulletin de la Société herpétologique de France, 157 : 49-51.

[24] Vacher J.-P. (2015). Bilan de dix années de suivi des indicateurs de la biodiversité
en Alsace. Les effectifs de Pélobate brun *Pelobates fuscus*. Ciconia, 39 (2-3) : 137-143.

[23] Vacher J.-P. (2015). Bilan de dix années de suivi des indicateurs de la biodiversité
en Alsace. Richesse et diversité spécifiques des communautés d’amphibiens au sein d’un
réseau de mares. Ciconia, 39 (2-3) : 128-136.

[22] Vacher J.-P., Thiriet J., Michel V. (2015). Distribution, ecology, and status of the
Common Wall Lizard *Podarcis muralis* (Laurenti, 1768), in Alsace, France. In Laufer H.,
Schulte U. (eds.). Verbreitung, Biologie und Schutz der Mauereidechse Podarcis muralis
(Laurenti, 1768). Mertensiella, 22: 70-73.

[21] Vacher J.-P., Miaud C., Dejean T. (2014). Une nouvelle espèce pour la fonge
d’Alsace : découverte de *Batrachochytrium dendrobatidis* Longcore, Pessier & Nichols,
1999 (Fungi: Rhizophydiales), champignon parasite des Amphibiens. Bulletin de la Société
d’Histoire naturelle et d’Ethnographie de Colmar, 71 : 39-48.

[20] Albinet S., Muratet J., Vacher J.-P. (2013). Herpétofaune de la commune de Toulouse,
Haute-Garonne (31). Bulletin de la Société Herpétologique de France, 147 : 351-376.

[19] Vacher J.-P. 2013 (2013). Le Sonneur à ventre jaune (*Bombina variegata*) en Alsace :
statut, menaces et plan régional d’actions. Ciconia, 37 (1-2) : 52-62.

[18] Vacher J.-P., Thiriet J., Michel V. (2013). Distribution, Ecology and Conservation
of the Smooth Newt *Lissotriton vulgaris* (Linnaeus, 1758), in Alsace, France. In Grosse
W.-R., Kühnel K.-D, Nöllert A. (eds.). Verbreitung, Biologie und Schutz des Teichmolches,
*Lissotriton vulgaris* (Linnaeus, 1758). Mertensiella, 19: 26-29.

[17] Graitson E., Hussin J., Vacher J.-P. (2012). Synthèse de 24 années de suivi d’une
communauté de reptiles typiques du nord de l’Europe. Bulletin de la Société Herpétologique
de France, 141 : 63-81.

[16] Vacher J.-P. (2010). Statut actuel de la grenouille des champs *Rana arvalis* Nilsson,
1842 (Amphibia : Ranidae) sur la bande rhénane en Alsace. Bulletin de la Société d’Histoire
naturelle et d’Ethnographie de Colmar, 69 : 3-12.

[15] Muratet J., Deso G., Vacher J.-P. (2010). Un cas de leucisme chez le Crapaud
commun *Bufo bufo* (Linné, 1758). Bulletin de la Société herpétologique de France, 134 :
51-54.

[14] Vacher J.-P., Falguier A., Pinston H., Craney E. (2008). The moor frog (*Rana arvalis*)
in Alsace and Franche-Comté (France) - past and present distribution. In Glandt D. & Jehle
R. (eds.). Der Moorfrosch/The Moor Frog. Zeitschrift für Feldherpetologie, Supplement
13: 283-290.

[13] Schmitt L., Lebeau M., Tremolieres M., Defraeye S., Coli, C., Denny E., Dillinger M.,
Beck T., Dor J.C., Gombert P., Gueidan A., Manne S., Party J.P., Perrotey P., Piquette
M., Roeck U., Schnitzler A., Sonnet O., Vacher J.P., Vauclin V., Weiss M., Zacher J.N.,
Wilms P. (2008). Le polder d’Erstein : objectifs, aménagements et retour d’expérience
sur cinq ans de fonctionnement et de suivi scientifique environnemental (Rhin, France).
Ingénieries n° spécial “La prévention des inondations. Aspects techniques et économiques
des aménagements de ralentissement dynamique des crues” : 67-84.

[12] Pottier G., Vacher J.-P., Savine N. (2006). Interrogations sur l’existence contemporaine
de la Couleuvre de Montpellier *Malpolon monspessulanus* (Hermann, 1804) (Reptilia,
Colubridae) en région Midi-Pyrénées (France). Bulletin de la Société Herpétologique de
France, 120 : 33-56.

[11] Hahn W., Vacher J.-P. (2006). Nouvelles données sur la répartition du Lézard vert
occidental *Lacerta bilineata* Daudin, 1802 (Sauria, Lacertidae) en Alsace. Bulletin de la
Société d’Histoire naturelle de Colmar, 67 : 27-34.

[10] Vacher J.-P., Rabet N., Cart J.-F., Godinat G. (2006). Nouvelles observations de
grands crustacés branchiopodes en Alsace. Bulletin de la Société d’Histoire naturelle et
d’Ethnographie de Colmar, 67 : 111-116.

[9] Vacher J.-P., Pottier G., Grosselet O. (2005). La distribution du Crapaud calamite
*Bufo calamita* Laurenti, 1768 (Anura, Bufonidae) dans les Pyrénées françaises. Bulletin de
la Société Herpétologique de France, 113-114 : 45-51.

[8] Vacher J.-P., Rufray X. (2005). Predation of *Pelobates fuscus* (Laurenti, 1768) by
the kingfisher *Alcedo atthis* (Linnaeus, 1758). Herpetozoa, 18 (3/4): 189-190.

[7] Albinet S., Vacher J.-P. (2005). Approche de la richesse herpétologique du nord de la
Dobroudja Roumaine et des environs de Sfantu Gheorghe. Bulletin de la Société d’Histoire
Naturelle du Tarn-et-Garonne, 29 : 31-36.

[6] Vacher J.-P., Dronneau C. (2004). Redécouverte du Triton crêté *Triturus cristatus*
(Laurenti, 1768) dans l’île de Rhinau (Bas-rhin). Ciconia, 27 (2) : 81-82.

[5] Vacher J.-P., Presseq B., Bertrand A. (2003). Découverte du Seps strié *Chalcides
striatus* (Cuvier, 1829) (Squamata, Scincidae) dans le département de la Haute-Garonne.
Bulletin de la Société Herpétologique de France, 105 : 4-8.

[4] Pottier G., Arlot P., Dohogne R., Vacher J.-P. (2001). Nouvelles données sur la
distribution de la Vipère de Séoane *Vipera seoanei* Lataste , 1879 (Ophidia, Viperidae) en
France. Bulletin de la Société Herpétologique de France, 99 : 37-44.

[3] Vacher J.-P., Dewynter M., Marty C., Blanc M. (2001). New records for *Drepanoides
anomalus* (Jan, 1863) in French Guiana. Herpetozoa, 14 (3/4): 135-137.

[2] Vacher J.-P. (2001). Nouvelles observations d’*Oxygastra curtisii* (Dale, 1834) dans le
département de la Haute-Garonne (Odonata, Corduliidae). Martinia, 17 (2) : 67-68.

[1] Vacher J.-P. (1999). Record d’altitude en France pour le lézard hispanique *Podarcis hispanica* (Steindachner, 1870) (Squamata, Lacertidae). Bulletin de la Société Herpétologique
de France, 92 : 53-55.

